### PR TITLE
Update extract-frontmatter from v2.1.0 to v4.1.1

### PR DESCRIPTION
**Pull request by Kage-Yami**
I'm getting back into doing a bit of Rust dev, and on a bit of a whim, I decided to rewrite `extract-frontmatter` (I wasn't the happiest with it to begin with).

Given it was a bit arbitrary (and there's not too many consuming crates at the moment), I figured I'd do a PR that updates it for Acid.

It wasn't entirely clear to me how to easily test this locally, but it at least builds. I also think Sedum uses the same front-matter delimiter config as you, and I found that `v4.0.0` of `extract-frontmatter` didn't support it, so that should be good already in `v4.1.0`. 🙂 (Details are available in the [GitLab issue](https://gitlab.com/isekai/libraries/rust/extract-frontmatter/-/issues/4), if you're interested.)

### CODE REVIEW

**Comment by iamtheblackunicorn** [comment]
@Kage-Yami Yo, I'm sorry that I'm replying so late!! First of all, thank you for doing this and secondly, I notice when I try to retrieve URLs in front matter, It doesn't retrieve them. Any suggestions? Is that fixed in v.4.1.0? Also, this:
```markdown
layout:post
title:A sample
```
works. This, however:
```markdown
layout: post
title: A sample
```
doesn't work.

**Comment by Kage-Yami** [comment]
Hmm, I'll be able to have a closer look later to make sure there's not some weird edge-case quirk, but generally, outside of stripping the prefix from each line of matter with a modifier (if desired), `extract-frontmatter` won't touch the front-matter at all - it will simply do a split to return it and the data as separate string slices, that you would then parse as whatever format you need. (For example, my original prompt in writing the crate was to pull out JSON metadata stored as comments within OpenSCAD scripts; not your typical markdown-with-YAML-frontmatter scenario.)

If you can link to or post some code showing your examples working / not working, I can take a closer look. But I suspect off the top of my head that it's nothing to do with `extract-frontmatter`.

**Comment by Kage-Yami** [comment]
Without anything else to go by yet, I threw together a couple of tests locally, and they both pass:

```rust
use extract_frontmatter::config::Splitter;
use extract_frontmatter::Extractor;
use std::borrow::Cow;

#[test]
fn url() {
    const DOC: &str = concat!("---\n", "url:https://example.com/\n", "---\n", "DATA");

    assert_eq!(
        Extractor::new(Splitter::EnclosingLines("---")).extract(DOC),
        (Cow::Borrowed(concat!("url:https://example.com/\n")), "DATA")
    );
}

#[test]
fn layout_and_title() {
    const WORKING: &str = concat!(
        "---\n",
        "layout:post\n",
        "title:A sample\n",
        "---\n",
        "DATA"
    );

    const BROKEN: &str = concat!(
        "---\n",
        "layout: post\n",
        "title: A sample\n",
        "---\n",
        "DATA"
    );

    assert_eq!(
        Extractor::new(Splitter::EnclosingLines("---")).extract(WORKING),
        (
            Cow::Borrowed(concat!("layout:post\n", "title:A sample\n")),
            "DATA"
        )
    );

    assert_eq!(
        Extractor::new(Splitter::EnclosingLines("---")).extract(BROKEN),
        (
            Cow::Borrowed(concat!("layout: post\n", "title: A sample\n")),
            "DATA"
        )
    );
}

```

**Comment by iamtheblackunicorn** [comment]
@Kage-Yami Hi, Joel! First of all, thank you for your contribution! I suspect that the issues I described might be due to the outdated version I used earlier. The test snippet above seems fine and seems to work. So, thank you again for striking that from my to-do list! :heart:

**Pull request merged**
